server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import:
    - optional:.env
  datasource:
    url: ${DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000 # 30 seconds
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    
